version: "2"
services:
  indico-web: &indico-web
    image: indico-cnea
    # image: getindico/indico:latest
    command: /opt/indico/run_indico.sh
    depends_on:
      - indico-redis
      - indico-celery
    ports:
      - "9090:59999"  # tcp socket port
    networks:
      - backend
      - frontend
      - postgresnet
    env_file:
      - indico.env
    volumes:
      - 'archive:/opt/indico/archive'
      - './data/log/nginx:/opt/indico/log/nginx'
      - 'customization:/opt/indico/custom'
      - 'static-files:/opt/indico/static'
      - './indico/worker/run_indico.sh:/opt/indico/run_indico.sh'
    tmpfs:
      - /opt/indico/tmp
  indico-static:
    build: indico/static
    networks:
      - frontend
  indico-celery:
    <<: *indico-web
    networks:
      - backend
      - postgresnet
    depends_on:
      - indico-redis
    command: /opt/indico/run_celery.sh
    ports: []
    volumes:
      - 'archive:/opt/indico/archive'
      - './indico/worker/run_celery.sh:/opt/indico/run_celery.sh'
  indico-redis:
    image: redis
    networks:
      - backend
    volumes:
      - './data/redis:/data'
#  indico-postgres:
#    image: centos/postgresql-96-centos7
#    networks:
#      - backend
 #   environment:
 #     - POSTGRESQL_USER=indico
  #    - POSTGRESQL_PASSWORD=indicopass
  #    - POSTGRESQL_DATABASE=indico
  #    - POSTGRESQL_ADMIN_PASSWORD=indicopass
  indico-nginx:
    build: nginx
    networks:
      - frontend
    env_file:
      - indico.env
    ports:
      - "8080:8080"
    volumes_from:
      - indico-web
volumes:
  archive:
  static-files:
  customization:
networks:
  backend: {}
  frontend: {}
  postgresnet:
    external: true