name: CI

on:
  push:
    branches: [ci-testing]

jobs:
  test:
    name: Test docker compose build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare config
        run: |
          cd indico-prod
          pip install yq
          ~/.local/bin/yq '. | .services["indico-web"].build = "./worker"' docker-compose.yml > docker-compose.local.yml

      - name: Build containers
        run: cd indico-prod && docker compose -f docker-compose.local.yml build

      - name: Test if Indico works
        run: ./indico-prod/test.sh
